/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    'action': string;
    'name': string;
    'result': string;
  }
  interface YooMapGl {}
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLYooMapGlElement extends Components.YooMapGl, HTMLStencilElement {}
  var HTMLYooMapGlElement: {
    prototype: HTMLYooMapGlElement;
    new (): HTMLYooMapGlElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'yoo-map-gl': HTMLYooMapGlElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    'action'?: string;
    'name'?: string;
    'result'?: string;
  }
  interface YooMapGl extends JSXBase.HTMLAttributes<HTMLYooMapGlElement> {}

  interface IntrinsicElements {
    'my-component': MyComponent;
    'yoo-map-gl': YooMapGl;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


